### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lucamuscat** [lucamuscat/perfsephone#8]
# Roadmap
The following is a list of features which I wish to see in perfsephone:
* [ ] `pytest-xdist` integration -- pytest-xdist is the standard way of parallelizing test execution. In order for perfsephone to work well with this plugin, perfsephone needs to work with pytest-xdist in mind;
* [ ] Automatically profiling multiple threads -- Currently, perfsephone only profiles the main thread. Frameworks such as Fastapi do not execute code on the main thread, but on external thread pools, consequently leading to the interesting code not being profiled;
* [ ] Automatically profiling multiple processes -- Similar to viztrace's follow fork feature, every new multiprocess spawned by python should be profiled;
* [ ]  Allow perfsephone to use Function-Entry-Exit (FEE) tracing along with callstack sampling;
* [ ] Replace JSON Chrome Event Format with the [Fuschia trace format (FTF)](https://fuchsia.dev/fuchsia-src/reference/tracing/trace-format), or perfetto's protobuf format;
* [ ] Output trace formats other than perfetto, such as speedscope;
* [ ] Add integration tests, which pull some popular python projects, and runs their pytest test suite under perfsephone;
* [ ] Benchmark perfsephone's overhead.
